# Generated by Django 5.0.7 on 2024-07-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payments_options_payments_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='paid_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='paid_lesson',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='payment_method',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='date_of_payment',
            new_name='paid_at',
        ),
    ]
