# Generated by Django 5.0.7 on 2024-08-03 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата и время обновления'),
        ),
    ]
