# Generated by Django 5.0.7 on 2024-08-03 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время обновления'),
        ),
    ]
